### ISSUE TITLE
Proposal: project creation wizard

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade-vscode#21]
Right now there are two ways of creating a Brigade project:

- through the `brig` CLI
- through the `brigade-project` Helm chart

As a user who is not experienced with Kubernetes or CLI tools, I would like a simple wizard that would help me create projects.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.

But note that v2 has `brig init` precisely for this reason.
